### ISSUE TITLE
Wrong "Latest" Release Tag

### ISSUE THREAD

**Issue by 7HE-W0R1D** [Seeed-Studio/Gesture_PAJ7620#15]
Hi! First I want to thank you all for this library. However, when I was installing it in Arduino IDE and VSCode, I noticed that the latest version they can find is 2.0.0, which contains compile error that breaks the code. This is also the case when you access this repo and click "release" to download - it shows version 2.0.0 here:

![Image](https://github.com/user-attachments/assets/eb432e79-7331-4329-9a0d-db2a625c676f)

I believe this can be solved by simply marking 2.0.1 as latest, so people like me would not be confused by why the code does not work at all.

**Comment by Lesords** [comment]
Hello，

What is your compilation problem?

Have you used the latest code in this repository? Why do you think that releasing a release will solve your problem?

**Comment by 7HE-W0R1D** [comment]
Hi, let me clarify the issue:

Problem: Your repository currently has version 2.0.0 tagged as "latest", but this version has compilation errors. When users install the library through Arduino IDE or VSCode or simply with Github /latest, they automatically get version 2.0.0 (the broken one) instead of 2.0.1 (the working one).

Solution: I think simply updating the GitHub release tags to mark version 2.0.1 as "latest" instead of 2.0.0 will fix this. This will ensure users automatically receive the working version.

I can upload error messages I get from 2.0.0 later today if that helps. But I do want to mention again that everything is working perfectly with 2.0.1

**Comment by Lesords** [comment]
I'm a little confused, where did you get the 2.0.1 version of the code?

Is it the latest code in this repository?

**Comment by 7HE-W0R1D** [comment]
> ~I'm a little confused, where did you get the 2.0.1 version of the code?~
> 
> ~Is it the latest code in this repository?~
> 
> ~Update：I know what you mean.~
> 
> Update：You mean v2.1.0 instead of 2.0.1, right?

Yes exactly, I should have attached a screenshot of that as well. Thanks for fixing that! I'll close the issue now :)
